import 'package:flutter/material.dart';
import 'package:secure_nagrik/Page4.dart';
import 'package:awesome_snackbar_content/awesome_snackbar_content.dart';

class Page3 extends StatefulWidget {
  const Page3({Key? key}) : super(key: key);

  @override
  _Page3State createState() => _Page3State();
}

class _Page3State extends State<Page3> {
  final List<Map<String, String>> _messages = [
    {
      'sender': 'PAYTM-BK',
      'message':
      'Your OPT for transaction at AMAZON.IN for Rs. 9810/- is ******. Do not share this with anyone. Transaction not generated by you ? Call 1800-0000-0000 or email us at hdfc-bank@gmail.com'
    },
  ];

  final TextEditingController _textEditingController =
  TextEditingController();

  bool _isOnCall = true;

  void _sendMessage(String message) {
    if (message.isNotEmpty) {
      setState(() {
        _messages.insert(0, {'sender': 'You', 'message': message});
      });
      _textEditingController.clear();
    }
  }

  void _showReportSentSnackbar() {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text('Report sent to cybercrime'),
        duration: Duration(seconds: 3),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('PAYTM-BK'),
        actions: [
          IconButton(
            icon: Icon(Icons.report),
            onPressed: () {
              showDialog(
                context: context,
                builder: (BuildContext context) => AlertDialog(
                  title: Text('Report this message'),
                  content: Text('Do you want to automatically report this message or manually report it?'),
                  actions: [
                    TextButton(
                      child: const Text('Automatically'),
                      onPressed: () {
                        Navigator.pop(context, true);
                        final snackBar = SnackBar(
                          elevation: 0,
                          behavior: SnackBarBehavior.floating,
                          backgroundColor: Colors.transparent,
                          content: AwesomeSnackbarContent(
                            title: 'Report sent',
                            message:
                            'Report with all the necessary details sent to the cybercrime department :)!',
                            contentType: ContentType.success,
                          ),
                        );

                        ScaffoldMessenger.of(context)
                          ..hideCurrentSnackBar()
                          ..showSnackBar(snackBar);
                      },
                    ),
                    TextButton(
                      child: Text('Manually'),
                      onPressed: () {
                          // code to manually report the message
                      },
                    ),
                  ],
                ),
              );
            },
          ),
        ],
      ),
    body: Column(
    children: [
    Container(
    padding: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
    margin: EdgeInsets.symmetric(vertical: 10, horizontal: 10),
    decoration: BoxDecoration(
    color: Colors.yellow.withOpacity(0.8),
    borderRadius: BorderRadius.circular(10),
    ),
    child: GestureDetector(
    onTap:() {
      showDialog(
        context: context,
        builder: (BuildContext context) =>
            AlertDialog(
              title: const Text('Warning'),
              content: const Text(
                  'Please disconnect the call to read the OTP. Do not share your OTP with anyone.'),
              actions: <Widget>[
                ElevatedButton(
                  onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (context) => Page4())),
                  child: const Text('Disconnect Call'),
                ),
                ElevatedButton(
                  onPressed: () => Navigator.pop(context, 'OK'),
                  child: const Text('Go Back'),
                ),
              ],
            ),
      );
    },
      child: Center(
        child: Text(
          'We have detected you are currently on a call and have hidden the OTP.',
          style: TextStyle(fontSize: 16),
          textAlign: TextAlign.center,
        ),
      ),
    ),
    ),
      Expanded(
        child: ListView.builder(
          reverse: true,
          itemCount: _messages.length,
          itemBuilder: (context, index) {
            return Container(
              padding: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
              alignment: _messages[index]['sender'] == 'You'
                  ? Alignment.centerRight
                  : Alignment.centerLeft,
              child: Container(
                decoration: BoxDecoration(
                  color: _messages[index]['sender'] == 'You'
                      ? Colors.blue[200]
                      : Colors.grey[300],
                  borderRadius: BorderRadius.circular(8),
                ),
                padding: EdgeInsets.all(16),
                child: Text(
                  _messages[index]['message']!,
                  style: TextStyle(fontSize: 16),
                ),
              ),
            );
          },
        ),
      ),
      Container(
        decoration: BoxDecoration(
          color: Colors.white,
          boxShadow: [
            BoxShadow(
              color: Colors.grey.withOpacity(0.5),
              spreadRadius: 5,
              blurRadius: 7,
              offset: Offset(0, 3),
            ),
          ],
        ),
        padding: EdgeInsets.symmetric(horizontal: 16),
        child: Row(
          children: [
            Expanded(
              child: TextField(
                controller: _textEditingController,
                decoration: InputDecoration(
                  hintText: 'Type a message...',
                  border: InputBorder.none,
                ),
                onSubmitted: _sendMessage,
              ),
            ),
            SizedBox(width: 16),
            IconButton(
              icon: Icon(Icons.send),
              onPressed: () => _sendMessage(_textEditingController.text),
            ),
          ],
        ),
      ),
    ],
    ),
// add the report button to the AppBar

    );
  }
}
