import 'package:flutter/material.dart';

import 'HomePage.dart';

class Page4 extends StatefulWidget {
  const Page4({Key? key}) : super(key: key);

  @override
  _Page4State createState() => _Page4State();
}

class _Page4State extends State<Page4> {
  final List<Map<String, String>> _messages = [
    {
      'sender': 'PAYTM-BK',
      'message':
      'Your OPT for transaction at AMAZON.IN for Rs. 9810/- is 578482. Do not share this with anyone. Transaction not generated by you ? Call 1800-0000-0000 or email us at hdfc-bank@gmail.com'
    },
  ];

  final TextEditingController _textEditingController = TextEditingController();

  void _sendMessage(String message) {
    if (message.isNotEmpty) {
      setState(() {
        _messages.insert(0, {'sender': 'You', 'message': message});
      });
      _textEditingController.clear();
    }
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      // Intercept the back button press event
      onWillPop: () async {
        // Navigate back to home page
        Navigator.pushReplacement(
          context,
          MaterialPageRoute(
            builder: (BuildContext context) => HomePage(),
          ),
        );
        return true;
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text('PAYTM-BK'),
        ),
        body: Column(
          children: [
            Expanded(
              child: ListView.builder(
                reverse: true,
                itemCount: _messages.length,
                itemBuilder: (context, index) {
                  return Container(
                    padding: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                    alignment: _messages[index]['sender'] == 'You'
                        ? Alignment.centerRight
                        : Alignment.centerLeft,
                    child: Container(
                      decoration: BoxDecoration(
                        color: _messages[index]['sender'] == 'You'
                            ? Colors.blue[200]
                            : Colors.grey[300],
                        borderRadius: BorderRadius.circular(8),
                      ),
                      padding: EdgeInsets.all(16),
                      child: Text(
                        _messages[index]['message']!,
                        style: TextStyle(fontSize: 16),
                      ),
                    ),
                  );
                },
              ),
            ),
            Container(
              decoration: BoxDecoration(
                color: Colors.white,
                boxShadow: [
                  BoxShadow(
                    color: Colors.grey.withOpacity(0.5),
                    spreadRadius: 5,
                    blurRadius: 7,
                    offset: Offset(0, 3),
                  ),
                ],
              ),
              padding: EdgeInsets.symmetric(horizontal: 16),
              child: Row(
                children: [
                  Expanded(
                    child: TextField(
                      controller: _textEditingController,
                      decoration: InputDecoration(
                        hintText: 'Type a message...',
                        border: InputBorder.none,
                      ),
                      onSubmitted: _sendMessage,
                    ),
                  ),
                  SizedBox(width: 16),
                  IconButton(
                    icon: Icon(Icons.send),
                    onPressed: () =>
                        _sendMessage(_textEditingController.text),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
